export enum ScreenName {
  home = 'HomeScreen',
  detail = 'DetailScreen',
  detailPager = 'detailPager',
  detailPagerContainer = 'detailPagerContainer',
  topics = 'AllTopicScreen',
  collections = 'AllCollection',
  allImage = 'AllImage',
  imagesLatest = 'ListImageLatestScreen',
  imagesPopular = 'ListImagePopularScreen',
  imagesOldest = 'ListImageOldestScreen',
  allTopic = 'ListTopic',
  allCollection = 'ListCollection',
  collectionPhotos = 'CollectionPhotos',
  topicPhotos = 'TopicPhotos',
  search = 'Search',
  searchResult = 'SearchResult',
  loginResult = 'LoginSuccess',
  login = 'LoginRequest',
  user = 'user',
  currentUser = 'currentUser',
  userCollections = 'userCollections',
  userPhotos = 'userPhotos',
}
