export enum Screens {
	home = "HomeScreen",
	detail = "DetailScreen",
	detailPager = "detailPager",
	topics = "AllTopicScreen",
	collections = "AllCollection",
	allImage = "AllImage",
	imagesLatest = "ListImageLatestScreen",
	imagesPopular = "ListImagePopularScreen",
	imagesOldest = "ListImageOldestScreen",
	collectionPhotos = "CollectionPhotos",
	topicPhotos = "TopicPhotos",
	search = "Search",
	searchResult = "SearchResult",
	loginResult = "LoginSuccess",
	login = "LoginRequest",
	user = "user",
	currentUser = "currentUser",
	userCollections = "userCollections",
	userPhotos = "userPhotos",
	editUserProfile = "editUserProfile",
	userStatistics = "userStatistics",
	createCollection = "createCollection",
}
