export enum ScreenName {
  home = 'HomeScreen',
  detail= 'DetailScreen',
  detailPager = 'detailPager',
  topics = 'AllTopicScreen',
  collections = 'AllCollection',
  allImage = 'AllImage',
  ListImageLatest = 'ListImageLatestScreen',
  ListImagePopular = 'ListImagePopularScreen',
  ListImageOldest = 'ListImageOldestScreen',
  ListTopic = 'ListTopic',
  ListCollection = 'ListCollection',
  CollectionPhotos = 'CollectionPhotos',
  TopicPhotos = 'TopicPhotos',
  SearchScreen = 'Search',
  SearchFilter = 'SearchFilter',
  SearchResult = 'SearchResult',
}